add lint and build github workflow, update husky hooks

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,29 +1,39 @@
-bun run format
+# bun run format
+# if [ $? -ne 0 ]; then
+#   echo "\033[0;31mFormatting failed. Push aborted.\033[0m"
+#   exit 1
+# fi
+# if [ $? -eq 0 ]; then
+#   echo "\033[0;32mFormatting passed.\033[0m"
+# fi
+
+# bun run lint
+# if [ $? -ne 0 ]; then
+#   echo "\033[0;31mLinting failed. Push aborted.\033[0m"
+#   exit 1
+# fi
+# if [ $? -eq 0 ]; then
+#   echo "\033[0;32mLinting passed.\033[0m"
+# fi
+
+bun run lint-staged
 if [ $? -ne 0 ]; then
-  echo "\033[0;31mFormatting failed. Push aborted.\033[0m"
+  echo "\033[0;31mlint-staged failed. Commit aborted.\033[0m"
   exit 1
 fi
 if [ $? -eq 0 ]; then
-  echo "\033[0;32mFormatting passed.\033[0m"
+  echo "\033[0;32mlint-staged passed.\033[0m"
 fi
 
-bun run lint
-if [ $? -ne 0 ]; then
-  echo "\033[0;31mLinting failed. Push aborted.\033[0m"
-  exit 1
-fi
-if [ $? -eq 0 ]; then
-  echo "\033[0;32mLinting passed.\033[0m"
-fi
 
-bun run build
-if [ $? -ne 0 ]; then
-  echo "\033[0;31mBuild process failed. Push aborted.\033[0m"
-  exit 1
-fi
-if [ $? -eq 0 ]; then
-  echo "\033[0;32mBuild process passed.\033[0m"
-fi
+# bun run build
+# if [ $? -ne 0 ]; then
+#   echo "\033[0;31mBuild process failed. Push aborted.\033[0m"
+#   exit 1
+# fi
+# if [ $? -eq 0 ]; then
+#   echo "\033[0;32mBuild process passed.\033[0m"
+# fi
 
 # bun run test
 # if [ $? -ne 0 ]; then
