update eslint config, add lint-staged, create safe console logger

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,11 @@
-bun run format
-if [ $? -ne 0 ]; then
-  echo "\033[0;31mFormatting failed. Commit aborted.\033[0m"
-  exit 1
-fi
-if [ $? -eq 0 ]; then
-  echo "\033[0;32mFormatting passed.\033[0m"
-fi
+# bun run format
+# if [ $? -ne 0 ]; then
+#   echo "\033[0;31mFormatting failed. Commit aborted.\033[0m"
+#   exit 1
+# fi
+# if [ $? -eq 0 ]; then
+#   echo "\033[0;32mFormatting passed.\033[0m"
+# fi
 
 # bun run lint
 # if [ $? -ne 0 ]; then
@@ -15,6 +15,8 @@ fi
 # if [ $? -eq 0 ]; then
 #   echo "\033[0;32mLinting passed.\033[0m"
 # fi
+
+bun run lint-staged
 
 BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
 echo "\033[0;35mCommitting changes to branch: '$BRANCH_NAME'\033[0m"
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,11 +1,11 @@
-# bun run format
-# if [ $? -ne 0 ]; then
-#   echo "\033[0;31mFormatting failed. Push aborted.\033[0m"
-#   exit 1
-# fi
-# if [ $? -eq 0 ]; then
-#   echo "\033[0;32mFormatting passed.\033[0m"
-# fi
+bun run format
+if [ $? -ne 0 ]; then
+  echo "\033[0;31mFormatting failed. Push aborted.\033[0m"
+  exit 1
+fi
+if [ $? -eq 0 ]; then
+  echo "\033[0;32mFormatting passed.\033[0m"
+fi
 
 bun run lint
 if [ $? -ne 0 ]; then
